<h1>Slicing Arrays</h1>

In [1]:
import numpy as np

In [2]:
A = np.array([5,8,0,2,4,6])

In [3]:
A[0]

5

In [4]:
A[-1]

6

In [5]:
A[-3]

2

In [7]:
A[300%6]

5

In [8]:
A.size

6

In [9]:
A[300%A.size]

5

In [10]:
B = np.arange(35).reshape(7,5)

In [11]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [12]:
B[2]

array([10, 11, 12, 13, 14])

In [13]:
B[-2]

array([25, 26, 27, 28, 29])

In [15]:
B[-2][0]

25

In [16]:
B[1,4]

9

In [17]:
B[2,3]

13

In [18]:
C = np.arange(20).reshape(5,2,2)

In [19]:
C

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [22]:
C[0,1]

array([2, 3])

In [25]:
C[0,1,1]

3

In [30]:
C[0,1,1] = 32
C

array([[[ 0,  1],
        [ 2, 32]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])