# Chapter 2 - Data Preparation Basics
## Segment 1 - Filtering and selecting data

In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

### Selecting and retrieving data
You can write an index value in two forms.
- Label index or 
- Integer index

In [2]:
series_obj = Series(np.arange(8), index=['row 1', 'row 2', 'row 3', 'row 4', 'row 5', 'row 6','row 7', 'row 8'])
series_obj

row 1    0
row 2    1
row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
row 8    7
dtype: int32

In [3]:
series_obj['row 7']

6

In [4]:
series_obj[[0, 7]]

row 1    0
row 8    7
dtype: int32

In [5]:
np.random.rand(36)

array([0.10800701, 0.06496634, 0.7698181 , 0.96006472, 0.18919325,
       0.25809371, 0.91351679, 0.79475083, 0.61750972, 0.87115881,
       0.24815099, 0.84786894, 0.64223894, 0.24333829, 0.02322581,
       0.09549717, 0.65415281, 0.72116127, 0.1520522 , 0.19657688,
       0.95852135, 0.81365813, 0.6688048 , 0.12856667, 0.54532839,
       0.91430049, 0.12801236, 0.94218273, 0.18941824, 0.95432279,
       0.05428345, 0.47037481, 0.60750176, 0.79630118, 0.11691928,
       0.37387031])

In [6]:
np.random.rand(36)

array([0.68965954, 0.71227412, 0.22592321, 0.75141517, 0.52065744,
       0.69279442, 0.57597754, 0.60938543, 0.99839389, 0.62180156,
       0.97707742, 0.19435225, 0.82926876, 0.59699814, 0.42298197,
       0.0261422 , 0.03194334, 0.39034525, 0.71459223, 0.52334313,
       0.76905564, 0.55142591, 0.70298322, 0.19636504, 0.0315493 ,
       0.99393928, 0.41028062, 0.19883173, 0.1011873 , 0.70561393,
       0.02470426, 0.00585387, 0.45747165, 0.47779383, 0.48441456,
       0.26059203])

In [7]:
np.random.seed(25)
np.random.rand(36)

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013,
       0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032,
       0.40236573, 0.1130407 , 0.44703085, 0.58544512, 0.1619851 ,
       0.52071879, 0.32605113, 0.69918624, 0.36639455, 0.83637451,
       0.48134294, 0.5165023 , 0.38304813, 0.9975409 , 0.51424449,
       0.55905327, 0.03444977, 0.71993003, 0.42100355, 0.43693513,
       0.28170075, 0.90027434, 0.66961228, 0.45606875, 0.28980434,
       0.52581896])

In [8]:
np.random.seed(25)
np.random.rand(36)

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013,
       0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032,
       0.40236573, 0.1130407 , 0.44703085, 0.58544512, 0.1619851 ,
       0.52071879, 0.32605113, 0.69918624, 0.36639455, 0.83637451,
       0.48134294, 0.5165023 , 0.38304813, 0.9975409 , 0.51424449,
       0.55905327, 0.03444977, 0.71993003, 0.42100355, 0.43693513,
       0.28170075, 0.90027434, 0.66961228, 0.45606875, 0.28980434,
       0.52581896])

In [9]:
np.random.seed(25)
np.random.rand(36)

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013,
       0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032,
       0.40236573, 0.1130407 , 0.44703085, 0.58544512, 0.1619851 ,
       0.52071879, 0.32605113, 0.69918624, 0.36639455, 0.83637451,
       0.48134294, 0.5165023 , 0.38304813, 0.9975409 , 0.51424449,
       0.55905327, 0.03444977, 0.71993003, 0.42100355, 0.43693513,
       0.28170075, 0.90027434, 0.66961228, 0.45606875, 0.28980434,
       0.52581896])

In [10]:
np.random.seed(25)
DF_obj = DataFrame(np.random.rand(36).reshape((6,6)),
                   index=['row 1', 'row 2', 'row 3', 'row 4','row 5','row 6'],
                   columns=['column 1','column 2','column 3','column 4','column 5','column 6'])
DF_obj

column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819

In [11]:
DF_obj.loc[['row 2', 'row 5'], ['column 5', 'column 2']]

column 5  column 2
row 2  0.402366  0.437611
row 5  0.421004  0.559053

In [12]:
DF_obj.iloc[[2,5],[5,2]]

column 6  column 3
row 3  0.699186  0.161985
row 6  0.525819  0.669612

In [13]:
DF_obj.iloc[[1,4],[4,1]] #indexing starts at 0 in python

column 5  column 2
row 2  0.402366  0.437611
row 5  0.421004  0.559053

### Data slicing
You can use slicing to select and return a slice of several values from a data set. Slicing uses index values so you can use the same square brackets when doing data slicing.

How slicing differs, however, is that with slicing you pass in two index values that are separated by a colon. The index value on the left side of the colon should be the first value you want to select. On the right side of the colon, you write the index value for the last value you want to retrieve. When you execute the code, the indexer then simply finds the first record and the last record and returns every record in between them. 

In [15]:
series_obj['row 3': 'row 7']

row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
dtype: int32

In [17]:
series_obj[2:7] #during slicing last digit is exclusive

row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
dtype: int32

### Comparing with scalars
Now we're going to talk about comparison operators and scalar values. Just in case you don't know that a scalar value is, it's basically just a single numerical value. You can use comparison operators like greater than or less than to return true/false values for all records to indicate how each element compares to a scalar value.

In [18]:
DF_obj < .2

column 1  column 2  column 3  column 4  column 5  column 6
row 1     False     False     False      True     False      True
row 2     False     False     False     False     False      True
row 3     False     False      True     False     False     False
row 4     False     False     False     False     False     False
row 5     False     False      True     False     False     False
row 6     False     False     False     False     False     False

In [19]:
DF_obj[DF_obj < .2]

column 1  column 2  column 3  column 4  column 5  column 6
row 1       NaN       NaN       NaN  0.185911       NaN  0.117376
row 2       NaN       NaN       NaN       NaN       NaN  0.113041
row 3       NaN       NaN  0.161985       NaN       NaN       NaN
row 4       NaN       NaN       NaN       NaN       NaN       NaN
row 5       NaN       NaN  0.034450       NaN       NaN       NaN
row 6       NaN       NaN       NaN       NaN       NaN       NaN

In [26]:
DF_obj[DF_obj < .2].dropna()

Empty DataFrame
Columns: [column 1, column 2, column 3, column 4, column 5, column 6]
Index: []

In [27]:
DF_obj[DF_obj < .2].fillna(0)

column 1  column 2  column 3  column 4  column 5  column 6
row 1       0.0       0.0  0.000000  0.185911       0.0  0.117376
row 2       0.0       0.0  0.000000  0.000000       0.0  0.113041
row 3       0.0       0.0  0.161985  0.000000       0.0  0.000000
row 4       0.0       0.0  0.000000  0.000000       0.0  0.000000
row 5       0.0       0.0  0.034450  0.000000       0.0  0.000000
row 6       0.0       0.0  0.000000  0.000000       0.0  0.000000

### Filtering with scalars

In [24]:
series_obj[series_obj > 3]

row 5    4
row 6    5
row 7    6
row 8    7
dtype: int32

### Setting values with scalars

In [25]:
series_obj['row 1', 'row 5', 'row 8'] = 8
series_obj

row 1    8
row 2    1
row 3    2
row 4    3
row 5    8
row 6    5
row 7    6
row 8    8
dtype: int32

Filtering and selecting using Pandas is one of the most fundamental things you'll do in data analysis. Make sure you know how to use indexing to select and retrieve records.