# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [6]:
standardized_X_test[0:10,]

array([[-1.41139273,  0.52033312, -1.45642582, -1.43433496],
       [ 0.32189659, -0.92058937,  1.07563524,  0.22066692],
       [-1.03997359,  0.52033312, -1.51531096, -1.43433496],
       [-1.03997359,  0.76048687, -1.39754068, -1.43433496],
       [ 1.31234762,  0.28017937,  0.95786496,  1.18608467],
       [ 0.56950935, -1.16074311,  0.66343925,  0.35858374],
       [-0.04952255, -0.92058937,  0.13347299, -0.05516673],
       [-0.04952255, -0.68043562,  0.78120954,  0.91025103],
       [-0.91616721, -1.16074311, -0.45537842, -0.19308355],
       [-0.42094169, -1.40089686, -0.04318244, -0.33100037]])

In [8]:
y_train.ravel()

array([1, 1, 2, 0, 2, 1, 0, 2, 1, 1, 0, 1, 2, 1, 2, 2, 2, 0, 2, 0, 0, 2,
       0, 2, 1, 1, 2, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 2, 2, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 1, 0,
       1, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2,
       2, 0, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 2, 1, 2, 2, 2, 0, 0])

In [7]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [9]:
y_pred = perceptron.predict(standardized_X_test)

In [10]:
print(y_test)

[0 2 0 0 2 1 1 2 1 1 1 2 0 1 0 0 1 2 1 2 2 0 2 1 1 1 0 0 2 2]


In [11]:
print(y_pred)

[0 2 0 0 2 2 0 2 0 0 0 2 0 0 0 0 2 2 1 2 2 0 2 0 2 2 0 0 2 2]


In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75         9
           1       1.00      0.09      0.17        11
           2       0.71      1.00      0.83        10

    accuracy                           0.67        30
   macro avg       0.77      0.70      0.58        30
weighted avg       0.78      0.67      0.56        30

