# Chapter 6 - Other Popular Machine Learning Models Models
## Segment 3 - Instance-based learning w/ k-Nearest Neighbor
#### Setting up for classification analysis

In [6]:
import numpy as np
import pandas as pd

import scipy
import urllib
import sklearn

import matplotlib.pyplot as plt
from pylab import rcParams

from sklearn import neighbors
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
np.set_printoptions(precision=4, suppress=True) 
%matplotlib inline
rcParams['figure.figsize'] = 7, 4
plt.style.use('seaborn-whitegrid')

## Importing your data

In [9]:
address = r'/home/sp/sp/Master Python for Datascience/10Python Datascience Essentials part2/Python Datascience Essentials2 Exercise Files/Data/mtcars.csv'

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

X_prime = cars[['mpg', 'disp', 'hp', 'wt']].values
y = cars.iloc[:,9].values

In [10]:
X = preprocessing.scale(X_prime)

In [13]:
X_prime

array([[ 21.   , 160.   , 110.   ,   2.62 ],
       [ 21.   , 160.   , 110.   ,   2.875],
       [ 22.8  , 108.   ,  93.   ,   2.32 ],
       [ 21.4  , 258.   , 110.   ,   3.215],
       [ 18.7  , 360.   , 175.   ,   3.44 ],
       [ 18.1  , 225.   , 105.   ,   3.46 ],
       [ 14.3  , 360.   , 245.   ,   3.57 ],
       [ 24.4  , 146.7  ,  62.   ,   3.19 ],
       [ 22.8  , 140.8  ,  95.   ,   3.15 ],
       [ 19.2  , 167.6  , 123.   ,   3.44 ],
       [ 17.8  , 167.6  , 123.   ,   3.44 ],
       [ 16.4  , 275.8  , 180.   ,   4.07 ],
       [ 17.3  , 275.8  , 180.   ,   3.73 ],
       [ 15.2  , 275.8  , 180.   ,   3.78 ],
       [ 10.4  , 472.   , 205.   ,   5.25 ],
       [ 10.4  , 460.   , 215.   ,   5.424],
       [ 14.7  , 440.   , 230.   ,   5.345],
       [ 32.4  ,  78.7  ,  66.   ,   2.2  ],
       [ 30.4  ,  75.7  ,  52.   ,   1.615],
       [ 33.9  ,  71.1  ,  65.   ,   1.835],
       [ 21.5  , 120.1  ,  97.   ,   2.465],
       [ 15.5  , 318.   , 150.   ,   3.52 ],
       [ 1

In [14]:
y

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [11]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=.2, random_state=17)

In [15]:
X_train

array([[ 2.3279, -1.3085, -1.2105, -1.4353],
       [ 0.9962, -0.9052, -0.8252, -1.1186],
       [-0.7233,  0.986 ,  1.7384, -0.0491],
       [ 0.2207,  0.2236, -0.5437, -0.0023],
       [ 0.4567, -1.006 , -0.7956, -0.9317],
       [-0.3861, -0.5174, -0.351 ,  0.2313],
       [ 0.4567, -0.7371, -0.7659, -0.0698],
       [-0.1501, -0.5174, -0.351 ,  0.2313],
       [-0.8582,  0.5761,  2.7905,  0.3663],
       [-1.6336,  1.9779,  0.8641,  2.1107],
       [ 0.1533, -0.5798, -0.5437, -0.3554],
       [-0.7739,  0.7155,  0.0491,  0.3144],
       [-0.4704,  0.3695,  0.4936,  0.5324],
       [ 0.2376, -0.9068, -0.7363, -0.7811],
       [ 0.7265, -0.6888, -1.2549, -0.0283],
       [-0.2344,  1.0598,  0.4195,  0.2313],
       [ 1.7379, -1.1118, -0.4992, -1.7696],
       [-0.8244,  0.3695,  0.4936,  0.5843],
       [-0.9087,  1.7156,  1.2346,  2.2094],
       [ 1.2153, -1.2438, -1.1957, -1.3315],
       [-0.8244,  0.6007,  0.0491,  0.2261],
       [-0.9762,  1.0598,  1.4568,  0.3663],
       [ 0

In [16]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0])

In [17]:
X_test

array([[ 0.1533, -0.5798, -0.5437, -0.6202],
       [ 1.7379, -1.2708, -1.4031, -1.6637],
       [-1.1447,  0.9778,  1.4568,  0.6466],
       [-0.6222,  0.3695,  0.4936,  0.8855],
       [-0.3356, -0.0469, -0.6177,  0.2521],
       [-0.1501,  1.3877,  0.4195,  0.6518],
       [-0.0659, -0.7027,  0.4195, -0.4644]])

In [18]:
y_test

array([1, 1, 0, 0, 0, 0, 1])

## Building and training your model with training data

In [19]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)
print(clf)

KNeighborsClassifier()


## Evaluating your model's predictions

In [20]:
y_pred= clf.predict(X_test)
y_expect = y_test

print(metrics.classification_report(y_expect, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.90      0.83      0.84         7
weighted avg       0.89      0.86      0.85         7



In [21]:
y_pred

array([1, 1, 0, 0, 0, 0, 0])