<h1>Boolean Mask Arrays</h1>

In [1]:
import numpy as np

In [2]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [3]:
zero_mod_7_mask = 0 == (my_vector % 7)

In [4]:
my_vector % 7

array([4, 3, 0, 2, 0, 2, 0])

In [5]:
zero_mod_7_mask 

array([False, False,  True, False,  True, False,  True])

In [6]:
zero_mod_7_mask = 2 == (my_vector % 7)

In [7]:
zero_mod_7_mask

array([False, False, False,  True, False,  True, False])

In [9]:
sub_array = my_vector[zero_mod_7_mask]

In [10]:
sub_array

array([ 2, 37])

In [11]:
A = np.array([2,4,5,3,6,7,8,1])
A

array([2, 4, 5, 3, 6, 7, 8, 1])

In [15]:
div_2 = 0 == (A%2)

In [20]:
A[div_2]

array([2, 4, 6, 8])

In [30]:
C = [2,4,5,3,6,7,8,1]
list(filter((lambda x: x%2==0),C))

[2, 4, 6, 8]

In [31]:
[x for x in C if x%2==0]

[2, 4, 6, 8]

In [32]:
{x for x in C if x%2==0}

{2, 4, 6, 8}

In [35]:
list(x for x in C if x%2==0)

[2, 4, 6, 8]

In [36]:
mod_test = 0 == (my_vector % 7)

In [38]:
pos_test = my_vector > 0

In [39]:
pos_test

array([False, False, False,  True,  True,  True,  True])

In [40]:
com_mask = np.logical_and(mod_test, pos_test)

In [42]:
my_vector[com_mask]

array([ 21, 105])