<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4,5])

In [3]:
A

array([1, 2, 3, 4, 5])

In [6]:
B = np.arange(3,11).reshape(4,2)

In [7]:
B

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
C = np.random.randn(9).reshape(3,3)

In [9]:
C

array([[-0.64474154,  1.35814154, -1.39341237],
       [-1.06267181,  1.6799619 ,  0.83647085],
       [ 0.28083591, -0.92677578,  0.41907126]])

In [10]:
D = np.eye(4)

In [11]:
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
E = np.zeros(5)

In [13]:
E

array([0., 0., 0., 0., 0.])

In [14]:
F = np.array({2,3,4,5})

In [15]:
F

array({2, 3, 4, 5}, dtype=object)

In [16]:
G = np.array({1:2,3:4})

In [17]:
G

array({1: 2, 3: 4}, dtype=object)

In [21]:
A+E

array([1., 2., 3., 4., 5.])

In [24]:
I = np.linspace(1,5,6)

In [25]:
I

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [26]:
J = np.zeros((3,4,5))

In [27]:
J

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])